In [1]:
from copy import deepcopy
from time import time

import numpy as np

import board_tools as bt
from game_state import GameState

In [2]:
def generate_all_states(size):
    all_states = []
    game_states = [GameState(size)]

    i = 0

    while game_states:
        game_state = game_states.pop(0)
        # if game_state.board in all_states:
        #     return
        all_states.append(game_state.board)
        legal_moves = game_state.get_moves()
        for legal_move in legal_moves:
            next_game_state = deepcopy(game_state)
            next_game_state.make_move(legal_move)
            game_states.append(next_game_state)

        i += 1
        if i % 200 == 0:
            not_zeros = np.sum(game_states[0].board != 0)
            # game_states[0].plot()
            print(i, not_zeros)


    return all_states

In [18]:
all_states3 = generate_all_states(3)
print(all_states3[-1])
print(len(all_states3))

[[1 1 1]
 [1 1 1]
 [1 1 1]]
47


In [4]:
start = time()
all_states = generate_all_states(4)
print(all_states[-1])
print(len(all_states))
print(time() - start)

200 9
400 9
600 9
800 10
1000 10
1200 10
1400 10
1600 10
1800 10
2000 11
2200 11
2400 11
2600 11
2800 11
3000 11
3200 11
3400 11
3600 11
3800 11
4000 11
4200 11
4400 11
4600 11
4800 11
5000 11
5200 11
5400 11
5600 11
5800 12
6000 12
6200 12
6400 12
6600 12
6800 12
7000 12
7200 12
7400 12
7600 12
7800 12
8000 12
8200 12
8400 12
8600 12
8800 12
9000 12
9200 12
9400 12
9600 12
9800 12
10000 12
10200 12
10400 12
10600 12
10800 12
11000 12
11200 12
11400 12
11600 12
11800 12
12000 12
12200 12
12400 12
12600 12
12800 12
13000 12
13200 12
13400 12
13600 12
13800 12
14000 12
14200 12
14400 12
14600 12
14800 12
15000 12
15200 12
15400 12
15600 13
15800 13
16000 13
16200 13
16400 13
16600 13
16800 13
17000 13
17200 13
17400 13
17600 13
17800 13
18000 13
18200 13
18400 13
18600 13
18800 13
19000 13
19200 13
19400 13
19600 13
19800 13
20000 13
20200 13
20400 13
20600 13
20800 13
21000 13
21200 13
21400 13
21600 13
21800 13
22000 13
22200 13
22400 13
22600 13
22800 13
23000 13
23200 13
23400 13
236

In [5]:
backup = np.array(all_states)

In [7]:
all_states = np.array(backup)

In [9]:
from tqdm import tqdm

In [22]:
b = len(all_states) * all_states.itemsize
kb = b / 1024
mb = kb / 1024
gb = mb / 1024
print(b, kb, mb, gb)

191401 186.9150390625 0.18253421783447266 0.0001782560721039772


In [14]:
unique_states = []

for i, state in enumerate(all_states):
    is_unique = True
    for unique_state in unique_states:
        if np.array_equal(state, unique_state):
            is_unique = False
            break
    if is_unique:
        unique_states.append(state)
    if i % 200 == 0:
        print(len(unique_states), i)

1 0
191 200
371 400
558 600
733 800
896 1000
1066 1200
1254 1400
1414 1600
1595 1800
1722 2000
1881 2200
2055 2400
2227 2600
2380 2800
2458 3000
2588 3200
2745 3400
2874 3600
3038 3800
3218 4000
3377 4200
3531 4400
3651 4600
3779 4800
3924 5000
4073 5200
4220 5400
4301 5600
4401 5800
4564 6000
4724 6200
4854 6400
4979 6600
5126 6800
5285 7000
5450 7200
5606 7400
5755 7600
5896 7800
6034 8000
6126 8200
6129 8400
6243 8600
6334 8800
6470 9000
6597 9200
6748 9400
6885 9600
6983 9800
7109 10000
7268 10200
7411 10400
7555 10600
7741 10800
7903 11000
8052 11200
8191 11400
8324 11600
8483 11800
8622 12000
8743 12200
8849 12400
8923 12600
8987 12800
9110 13000
9284 13200
9408 13400
9535 13600
9639 13800
9775 14000
9924 14200
10063 14400
10188 14600
10273 14800
10321 15000
10381 15200
10383 15400
10502 15600
10646 15800
10795 16000
10943 16200
11059 16400
11165 16600
11274 16800
11367 17000
11476 17200
11623 17400
11766 17600
11887 17800
12046 18000
12166 18200
12305 18400
12451 18600
12564 188

KeyboardInterrupt: 

In [15]:
g = GameState(4)

In [16]:
%%timeit -r 4 -n 1000
deepcopy(g)

7.85 µs ± 1.48 µs per loop (mean ± std. dev. of 4 runs, 1,000 loops each)


In [17]:
%%timeit -r 4 -n 1000
np.array(g.board)

1.1 µs ± 620 ns per loop (mean ± std. dev. of 4 runs, 1,000 loops each)
